### ISSUE TITLE
Aceptar o Rechazar Tareas

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/platform#4]
Similar al [Issue 3](https://github.com/ZBoxApp/platform/issues/3) cuando tengamos el Modulo de Tareas, serla importante que si está es asignada a otra persona, el receptor este **OBLIGADO** a Aceptar o Rechazar la tarea.

Con las mayorías de las aplicaciones de hoy se genera una ansiedad porque no se sabe si el asignado se enteró de la tarea.

**Comment by enahum** [comment]
Esto debería ser una funcionalidad directa del addon, pero estoy de acuerdo

**Comment by enahum** [comment]
En la nueva versión hay mensajes efímeros que permitirán que el addon pueda enviar un mensaje con alguna acción, esto permitirá aceptar o rechazar etc...

Cerrando este issue.
