### ISSUE TITLE
Mensajes perdidos

### ISSUE THREAD

**Issue by pbruna** [ZBoxApp/platform#5]
Como vimos en la conversación https://chat.zboxapp.com/zboxapp-com/pl/ikets1nfz3nhjku9oaj8oj3juy hay mensajes que no aparecen a todos los usuarios del canal.

Eso provocó un poco de confusión cuando estamos conversando un tema de soporte.

**Comment by enahum** [comment]
Ok los mensajes no están perdidos, pero por alguna razón no llegaron. ya estoy revisando a ver que puede estar pasando.

**Comment by enahum** [comment]
Ok definitivamente esto ocurre cuando se desconecta momentáneamente el websocket.

La gente de MM ya está al tanto y están reparando esto junto con el cuadro de escribir que se mantiene en amarillo al reconectar el websocket.

Dejemos el issue abierto hasta que este implementado.

**Comment by enahum** [comment]
fixed
